dbt_training_dw:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: admin
      pass: admin
      port: 5432
      dbname: postgres
      schema: public
      threads: 1
      # keepalives_idle: 0
      # connect_timeout: 10
  target: dev
